### ISSUE TITLE
Farbe und Status für todos 

### ISSUE THREAD

**Issue by 53845714nF** [tnutzmann/OSWC-Semesteraufgabe#1]
Ich will noch ein Color Attribut im `todo.py` einbauen und das `is_done` würde ich in ein Staus verwandel.
Diese können dann "TO DO", "DOING" oder "DONE" sein.

**Comment by tnutzmann** [comment]
Wäre das mit der Farbe nicht was fürs Frontend? Theoretisch lässt isDone int Werte zu also könnte man das in der DB speichern.

**Comment by 53845714nF** [comment]
Status ist jetzt is_done.
