### ISSUE TITLE
Perform action scheint errors zu werfen

### ISSUE THREAD

**Issue by tnutzmann** [tnutzmann/OSWC-Semesteraufgabe#6]
Internal server error wenn versucht wird eine create action auszuführen

**Comment by tnutzmann** [comment]
gleiches Problem bei allen actions

**Comment by tnutzmann** [comment]
Fehler scheint nach todo_list.py Zeile 153 zu liegen...

**Comment by 53845714nF** [comment]
Auch schon gesehen, ist frag mich jetzt ob das ein "Python Fehler" ist oder ob wir was im Docker machen müssen.

**Comment by tnutzmann** [comment]
Hab am dockerfile rechte für die DB hinzugefügt und logging mit importiert dachte der Fehler liegt im auslesen von Action aber scheint nicht so zu sein... evtl logging ausbauen und gucken was kommt

**Comment by tnutzmann** [comment]
Hab den Fehler fix kommt heute Abend

**Comment by 53845714nF** [comment]
Was wars?

**Comment by tnutzmann** [comment]
Noch nicht ganz raus ich weiß das es im Vorgang von todo to dB liegt
